MongoDB Driver Migration
ONSdigital/dp-recipe-api pull request #162
Opened 2021-05-25 18:17 UTC by Marianasilvago

### What

Update mongo config to add creds and CAfile.

### How to review

Check the code changes.

### Who can review

Anyone with understanding of golang and mongo-go-driver library.

2021-05-27 07:35 UTC, daiLlew reviewed
Looks fine to me but I'd feel more comfortable if someone else also took a look before approving.

2021-06-23 15:14 UTC, CarlHembrough requested changes
I am getting an `internal error` when trying to call the recipes endpoint `curl localhost:22300/recipes`. Does it require a specific version of MongoDB locally?

I checked that recipes exist in my local database, and that the recipes are returned OK with the current develop code.

Here is the error: 

```
"error": "Server Error caused by document is nil",
    "stack_trace": [
      {
        "file": "/Users/carl/code/dp-recipe-api/mongo/mongo.go",
        "function": "github.com/ONSdigital/dp-recipe-api/mongo.(*Mongo).GetRecipes",
        "line": 69
      },
      {
        "file": "/Users/carl/code/dp-recipe-api/api/handlers.go",
        "function": "github.com/ONSdigital/dp-recipe-api/api.(*RecipeAPI).RecipeListHandler",
        "line": 57
```

2021-06-24 06:15 UTC, CarlHembrough approved these changes

2021-06-24 11:27 UTC, CarlHembrough submitted a review, later dismissed

2021-07-12 11:47 UTC, CarlHembrough approved these changes

2021-07-12 11:52 UTC, CarlHembrough requested changes
Based on Nathans comment
```
POST /instances does not seem to be working - getting Server Error caused by update document must contain key beginning with '$'
```

2021-07-13 09:19 UTC, CarlHembrough approved these changes

2021-07-19 12:50 UTC, merged